CREATE todos (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, userId INT NOT NULL, name VARCHAR(255) NOT NULL, content TEXT NOT NULL, done BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE users (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, admin BOOLEAN DEFAULT false
);
